"""create monthly maintenance runs

Revision ID: 0eaa57a7d5f5
Revises: 8bbf78e358b1
Create Date: 2026-08-06 09:04:05.114864

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0eaa57a7d5f5'
down_revision: Union[str, Sequence[str], None] = '8bbf78e358b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('monthly_maintenance_runs',
    sa.Column('period', sa.String(length=7), nullable=False),
    sa.Column('run_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('period')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('monthly_maintenance_runs')
    # ### end Alembic commands ###
