"""add eliminated_round and user_game_scores

Revision ID: 8bbf78e358b1
Revises: 5d66390cd507
Create Date: 2026-08-05 14:35:32.569078

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8bbf78e358b1'
down_revision: Union[str, Sequence[str], None] = '5d66390cd507'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_game_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('game_key', sa.String(length=64), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('result_score', sa.Integer(), nullable=False),
    sa.Column('participation_score', sa.Integer(), nullable=False),
    sa.Column('survival_score', sa.Integer(), nullable=False),
    sa.Column('final_score', sa.Integer(), nullable=False),
    sa.Column('committed_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['game_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_game_scores_session_id'), 'user_game_scores', ['session_id'], unique=False)
    op.create_index(op.f('ix_user_game_scores_user_id'), 'user_game_scores', ['user_id'], unique=False)
    op.add_column('game_players', sa.Column('eliminated_round', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('game_players', 'eliminated_round')
    op.drop_index(op.f('ix_user_game_scores_user_id'), table_name='user_game_scores')
    op.drop_index(op.f('ix_user_game_scores_session_id'), table_name='user_game_scores')
    op.drop_table('user_game_scores')
    # ### end Alembic commands ###
