"""add autoreply msgcmd tables

Revision ID: 9c4d7e2a5f18
Revises: 3f8a2c9d1b47
Create Date: 2026-08-06 10:15:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c4d7e2a5f18'
down_revision: Union[str, Sequence[str], None] = '3f8a2c9d1b47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('autoreply_rule_sets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=16), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('source_checksum', sa.String(length=64), nullable=False),
    sa.Column('source_etag', sa.String(length=255), nullable=True),
    sa.Column('source_last_modified', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('total_rows', sa.Integer(), nullable=False),
    sa.Column('active_rows', sa.Integer(), nullable=False),
    sa.Column('disabled_rows', sa.Integer(), nullable=False),
    sa.Column('warning_count', sa.Integer(), nullable=False),
    sa.Column('imported_by_user_id', sa.Integer(), nullable=True),
    sa.Column('imported_at', sa.DateTime(), nullable=False),
    sa.Column('activated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['imported_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_id')
    )
    op.create_table('autoreply_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rule_set_id', sa.Integer(), nullable=False),
    sa.Column('source_row', sa.Integer(), nullable=False),
    sa.Column('command', sa.Text(), nullable=False),
    sa.Column('normalized_command', sa.Text(), nullable=False),
    sa.Column('message_template', sa.Text(), nullable=False),
    sa.Column('response_type', sa.String(length=16), nullable=False),
    sa.Column('media_file_id', sa.Text(), nullable=True),
    sa.Column('match_all', sa.Boolean(), nullable=False),
    sa.Column('reply_to_sender', sa.Boolean(), nullable=False),
    sa.Column('reply_to_replied', sa.Boolean(), nullable=False),
    sa.Column('admin_only', sa.Boolean(), nullable=False),
    sa.Column('disabled', sa.Boolean(), nullable=False),
    sa.Column('source_payload_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("source_row > 0", name='ck_autoreply_rules_source_row'),
    sa.CheckConstraint("command <> ''", name='ck_autoreply_rules_command'),
    sa.CheckConstraint("message_template <> ''", name='ck_autoreply_rules_message_template'),
    sa.ForeignKeyConstraint(['rule_set_id'], ['autoreply_rule_sets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rule_set_id', 'source_row', name='uq_autoreply_rules_set_row')
    )
    op.create_index(op.f('ix_autoreply_rules_rule_set_id'), 'autoreply_rules', ['rule_set_id'], unique=False)
    op.create_index('ix_autoreply_rules_set_disabled_row', 'autoreply_rules', ['rule_set_id', 'disabled', 'source_row'], unique=False)
    op.create_table('autoreply_sync_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=16), nullable=True),
    sa.Column('reason', sa.String(length=16), nullable=False),
    sa.Column('triggered_by_user_id', sa.Integer(), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.Column('source_checksum', sa.String(length=64), nullable=True),
    sa.Column('total_rows', sa.Integer(), nullable=True),
    sa.Column('active_rows', sa.Integer(), nullable=True),
    sa.Column('disabled_rows', sa.Integer(), nullable=True),
    sa.Column('warning_count', sa.Integer(), nullable=False),
    sa.Column('error_count', sa.Integer(), nullable=False),
    sa.Column('error_reference', sa.String(length=32), nullable=True),
    sa.Column('summary_json', sa.JSON(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['triggered_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_id')
    )

    # created_at/updated_at sengaja tidak diisi -- kolomnya sudah punya
    # server_default=func.now() jadi SQLite yang mengisi otomatis.
    autoreply_feature_table = sa.table(
        'features',
        sa.column('feature_key', sa.String),
        sa.column('enabled_globally', sa.Boolean),
    )
    op.bulk_insert(
        autoreply_feature_table,
        [
            {
                'feature_key': 'autoreply',
                'enabled_globally': False,
            }
        ],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DELETE FROM features WHERE feature_key = 'autoreply'")
    op.drop_table('autoreply_sync_runs')
    op.drop_index('ix_autoreply_rules_set_disabled_row', table_name='autoreply_rules')
    op.drop_index(op.f('ix_autoreply_rules_rule_set_id'), table_name='autoreply_rules')
    op.drop_table('autoreply_rules')
    op.drop_table('autoreply_rule_sets')
    # ### end Alembic commands ###
